/**
 * Money and the organization — Billing, Usage, Plans, Members, Integrations and
 * Notifications — signed in as an org admin against a stubbed platform
 * (stubs.ts), and once as a plain member. The processor's card field is a
 * stand-in served at its own address, so no card number is ever typed here.
 */
import { expect, test } from './fixture.ts'
import { mounted } from './mount.ts'
import { ORG, type Sent } from './signed.ts'
import { org as platform, PLANS } from './stubs.ts'

const find = (sent: Sent[], method: string, path: string) => sent.find((s) => s.method === method && s.path === path)

test('Billing shows the plan, the cards, the invoices, and cancels at the period end', async ({ page }, info) => {
  const sent = await platform(page)
  await page.goto('/-/settings/billing')
  await expect(page.getByText('Max plan')).toBeVisible()
  await expect(page.getByText('$100 a month. Renews on Oct 27, 2026.')).toBeVisible()
  await expect(page.getByText('Visa •••• 4242')).toBeVisible()
  await expect(page.getByText('Expires 12/27 · Default')).toBeVisible()
  await expect(page.getByText('Sep 1, 2026', { exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath('billing.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: info.outputPath('billing-390.png'), fullPage: true })
  await page.setViewportSize({ width: 1440, height: 900 })

  await page.getByRole('button', { name: 'View invoice INV-0042' }).click()
  const bill = page.getByRole('dialog')
  await expect(bill.getByText('Invoice INV-0042')).toBeVisible()
  await expect(bill.getByText('Max — September')).toBeVisible()
  const download = page.waitForEvent('download')
  await bill.getByRole('button', { name: 'Download PDF' }).click()
  expect((await download).suggestedFilename()).toBe('INV-0042.pdf')
  await page.screenshot({ path: info.outputPath('billing-invoice.png') })
  await bill.getByRole('button', { name: 'Close' }).click()

  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Cancel plan' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Your plan ends on Oct 27, 2026' })).toBeVisible()
  expect(find(sent, 'POST', '/v1/billing/subscriptions/sub_1/cancel')?.body).toEqual({ atPeriodEnd: true })
  await page.getByRole('button', { name: 'Keep plan' }).click()
  await expect(page.getByText('Your plan renews as before')).toBeVisible()

  await page.getByRole('button', { name: 'Remove Visa •••• 4242' }).click()
  await expect(page.getByText('No card on file.')).toBeVisible()
  expect(find(sent, 'DELETE', '/v1/billing/methods/pm_1')).toBeTruthy()

  await page.getByRole('button', { name: 'Adjust plan' }).click()
  await expect(page).toHaveURL(/\/-\/plans$/)
})

test('a card is added through the processor’s own field, and only its token is sent', async ({ page }, info) => {
  const sent = await platform(page, { cards: false })
  await page.goto('/-/settings/billing')
  await page.getByRole('button', { name: 'Add card' }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByLabel('Card number')).toBeVisible()
  await expect(dialog.getByText('Sandbox: use a test card. Nothing is charged.')).toBeVisible()
  await page.screenshot({ path: info.outputPath('billing-card.png') })
  await dialog.getByRole('button', { name: 'Save card' }).click()
  await expect(page.getByText('Mastercard •••• 4444 is saved')).toBeVisible()
  expect(find(sent, 'POST', '/v1/billing/methods')?.body).toEqual({ type: 'card', providerRef: 'cnon:test' })
})

test('Plans marks the current plan and upgrades with the saved card, yearly', async ({ page }, info) => {
  const sent = await platform(page, { paid: false })
  await page.goto('/-/plans')
  await expect(page.getByText('Plans that grow with you')).toBeVisible()
  const free = page.getByLabel('Free plan', { exact: true })
  await expect(free.getByRole('button', { name: 'Current plan' })).toBeDisabled()
  await expect(page.getByLabel('DNS Pro plan')).toHaveCount(0)
  await expect(page.getByLabel('Enterprise plan').getByText('Priced with our team for your organization.')).toBeVisible()
  const max = page.getByLabel('Max plan', { exact: true })
  await expect(max.getByText('$100', { exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath('plans.png'), fullPage: true })

  await page.getByRole('radio', { name: 'Yearly' }).click()
  await expect(max.getByText('$81.18', { exact: true })).toBeVisible()
  await expect(max.getByText('a month, $974.16 billed yearly')).toBeVisible()
  await max.getByRole('button', { name: 'Upgrade to Max' }).click()
  await expect(page.getByRole('dialog').getByText('Visa •••• 4242 is charged $974.16 now, and again every year until you cancel.')).toBeVisible()
  await page.getByRole('dialog').getByRole('button', { name: 'Upgrade', exact: true }).click()
  await expect(page.getByText(`${ORG} is on Max`, { exact: true })).toBeVisible()
  expect(find(sent, 'POST', '/v1/billing/subscribe/card')?.body).toEqual({ planId: 'max', paymentMethodId: 'pm_1', interval: 'year' })
  await expect(max.getByRole('button', { name: 'Current plan' })).toBeVisible()
  await expect(page.getByLabel('Dev plan').getByText('One paid plan at a time: Max ends before Dev begins.')).toBeVisible()

  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: info.outputPath('plans-390.png'), fullPage: true })
  await page.getByRole('button', { name: 'Back to billing' }).click()
  await expect(page).toHaveURL(/\/-\/settings\/billing$/)
})

test('Usage shows the limits, the balance and the month, buys more and sets a monthly limit', async ({ page }, info) => {
  const sent = await platform(page)
  await page.goto('/-/settings/usage')
  await expect(page.getByText('Today · 1,800 of 2,500 requests')).toBeVisible()
  await expect(page.getByText('This week · 3,000 of 12,000 requests')).toBeVisible()
  await expect(page.getByText('$30 of $100')).toBeVisible()
  await expect(page.getByText('$42', { exact: true })).toBeVisible()
  await expect(page.getByText('$15', { exact: true })).toBeVisible()
  await expect(page.getByText('$52.50', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('LLM', { exact: true })).toBeVisible()
  await expect(page.getByRole('progressbar')).toHaveCount(6)
  await page.screenshot({ path: info.outputPath('usage.png'), fullPage: true })

  await page.getByRole('button', { name: 'Buy more' }).click()
  await expect(page.getByText('Charged to Visa •••• 4242')).toBeVisible()
  await page.getByLabel('Amount in dollars').fill('25')
  await page.getByRole('button', { name: 'Add $25' }).click()
  await expect(page.getByText('$25 is added to the balance')).toBeVisible()
  expect(find(sent, 'POST', '/v1/billing/topup')?.body).toEqual({ amountCents: 2500, paymentMethodId: 'pm_1' })

  await expect(page.getByText('No monthly limit')).toBeVisible()
  await page.getByLabel('Monthly limit in dollars').fill('500')
  await page.getByRole('button', { name: 'Set limit' }).click()
  await expect(page.getByText('$500 a month', { exact: true })).toBeVisible()
  expect(find(sent, 'POST', '/v1/billing/alerts')?.body).toMatchObject({ threshold: 50000, enforce: true, project: '', service: '' })
  await page.getByLabel('Monthly limit in dollars').fill('800')
  await page.getByRole('button', { name: 'Change limit' }).click()
  await expect(page.getByText('$800 a month', { exact: true })).toBeVisible()
  expect(find(sent, 'PATCH', '/v1/billing/alerts/al_1')?.body).toEqual({ threshold: 80000 })

  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: info.outputPath('usage-390.png'), fullPage: true })
})

test('Members lists the roster by role, invites by email and revokes', async ({ page }, info) => {
  const sent = await platform(page)
  await page.goto('/-/settings/members')
  await expect(page.getByText(`${ORG}/dave · since Aug 1, 2026`)).toBeVisible()
  await expect(page.getByText('Owner', { exact: true })).toBeVisible()
  await expect(page.getByText('Admin', { exact: true })).toBeVisible()
  await expect(page.getByText('erin@acme.test')).toBeVisible()
  await page.screenshot({ path: info.outputPath('members.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: info.outputPath('members-390.png'), fullPage: true })
  await page.setViewportSize({ width: 1440, height: 900 })

  await page.getByLabel('Email to invite').fill('Amy.Lee@acme.test')
  await page.getByRole('button', { name: 'Invite' }).click()
  await expect(page.getByText('Amy.Lee@acme.test is invited. IAM sends no email: share the code with them.')).toBeVisible()
  const made = find(sent, 'POST', '/v1/iam/invitations')?.body as Record<string, unknown>
  expect(made).toMatchObject({ owner: ORG, email: 'amy.lee@acme.test', quota: 1, state: 'Active' })
  await expect(page.getByText('amy.lee@acme.test', { exact: true })).toBeVisible()

  await page.getByRole('button', { name: 'Revoke the invitation for erin@acme.test' }).click()
  await expect(page.getByText('erin@acme.test')).toHaveCount(0)
  expect(find(sent, 'DELETE', `/v1/iam/invitations/${ORG}/invite-erin-a1b2c3`)).toBeTruthy()
  expect(find(sent, 'GET', '/v1/iam/memberships')?.query).toBe(`?org=${ORG}`)
})

test('Integrations shows GitHub and Slack, disconnects Slack and installs the App through GitHub', async ({ page }, info) => {
  const sent = await platform(page)
  await page.route('https://github.com/**', (r) => r.fulfill({ contentType: 'text/html', body: '<title>GitHub</title>Install' }))
  await page.goto('/-/settings/integrations')
  await expect(page.getByText('Connected as @dave-gh')).toBeVisible()
  await expect(page.getByText('Organization · every repository')).toBeVisible()
  await expect(page.getByText('Acme HQ')).toBeVisible()
  await expect(page.getByText('general', { exact: true })).toBeVisible()
  await expect(page.getByText('Not joined')).toBeVisible()
  await page.screenshot({ path: info.outputPath('integrations.png'), fullPage: true })

  await page.getByRole('button', { name: 'Disconnect', exact: true }).nth(1).click()
  await expect(page.getByText('Slack is disconnected')).toBeVisible()
  expect(find(sent, 'POST', '/v1/provider/slack/disconnect')).toBeTruthy()
  await expect(page.getByRole('button', { name: 'Connect', exact: true })).toHaveCount(1)

  await page.getByRole('button', { name: 'Install on a GitHub account' }).click()
  await expect(page).toHaveURL('https://github.com/apps/hanzo/installations/new?state=signed')
})

test('Notifications adds a webhook, shows its secret once, tests it, reads its log and deletes it', async ({ page }, info) => {
  const sent = await platform(page)
  await page.goto('/-/settings/notifications')
  await expect(page.getByText('https://acme.test/hooks/orders')).toBeVisible()
  await expect(page.getByText('orders · commerce.order.> · 12 delivered, 1 failed this week')).toBeVisible()

  await page.getByRole('button', { name: 'Add webhook' }).click()
  await page.getByLabel('Endpoint URL').fill('http://acme.test/new')
  await page.getByRole('button', { name: 'Add webhook' }).click()
  await expect(page.getByText('A webhook is delivered over https only')).toBeVisible()
  await page.getByLabel('Endpoint URL').fill('https://acme.test/new')
  await page.getByLabel('Events').fill('event.>, commerce.order.paid')
  await page.getByLabel('Description', { exact: true }).fill('everything')
  await page.getByRole('button', { name: 'Add webhook' }).click()
  await expect(page.getByLabel('Signing secret')).toHaveText('whsec_0123456789abcdef')
  expect(find(sent, 'POST', '/v1/webhook')?.body).toEqual({ url: 'https://acme.test/new', events: ['event.>', 'commerce.order.paid'], description: 'everything' })
  await page.screenshot({ path: info.outputPath('notifications.png'), fullPage: true })

  await page.getByRole('button', { name: 'Send a test to https://acme.test/hooks/orders' }).click()
  await expect(page.getByText('The test reached https://acme.test/hooks/orders: 200 in 84 ms')).toBeVisible()
  await page.getByRole('button', { name: 'Deliveries to https://acme.test/hooks/orders' }).click()
  await expect(page.getByText('webhook.test → 200')).toBeVisible()
  await page.getByRole('button', { name: 'Delete https://acme.test/hooks/orders' }).click()
  await expect(page.getByText('https://acme.test/hooks/orders is deleted')).toBeVisible()
  expect(find(sent, 'DELETE', '/v1/webhook/wh_1')).toBeTruthy()

  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: info.outputPath('notifications-390.png'), fullPage: true })
})

test('a member reads the limits, the roster and the connectors, and changes none of the admin’s', async ({ page }, info) => {
  await platform(page)
  const b64 = (o: object) => Buffer.from(JSON.stringify(o)).toString('base64url')
  const member = [b64({ alg: 'none' }), b64({ sub: `${ORG}/zed`, email: 'zed@acme.test', orgs: [{ org: ORG, role: 'member' }] }), 'x'].join('.')
  await page.addInitScript((t) => localStorage.setItem('hanzo_iam_access_token', t), member)

  await page.goto('/-/settings/usage')
  await expect(page.getByText('An org admin sets the monthly limit.')).toBeVisible()
  await expect(page.getByLabel('Monthly limit in dollars')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Buy more' })).toHaveCount(0)
  await page.goto('/-/settings/billing')
  await expect(page.getByText('Invoices', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Add card' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: /^Remove / })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Cancel', exact: true })).toHaveCount(0)
  await page.goto('/-/plans')
  await expect(page.getByText('An org admin changes the plan.').first()).toBeVisible()
  await expect(page.getByRole('button', { name: /^Upgrade to / })).toHaveCount(0)
  await page.goto('/-/settings/notifications')
  await expect(page.getByRole('button', { name: 'Add webhook' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: /^Send a test to / })).toHaveCount(0)
  await page.goto('/-/settings/members')
  await expect(page.getByText('An org admin invites people and sees the open invitations.')).toBeVisible()
  await expect(page.getByLabel('Email to invite')).toHaveCount(0)
  await page.goto('/-/settings/integrations')
  await expect(page.getByText('An org admin connects the Slack workspace.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Install on a GitHub account' })).toHaveCount(0)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: info.outputPath('integrations-member-390.png'), fullPage: true })
})

test('a visitor sees the plans and is asked to sign in to choose one', async ({ page }) => {
  await page.route((u) => u.pathname === '/v1/billing/plans', (r) => r.fulfill({ json: PLANS }))
  await mounted(page, { path: '-/plans', org: null, admin: false, person: null, signIn: true })
  await expect(page.getByText('Sign in to see the plan you are on.')).toBeVisible()
  await expect(page.getByLabel('Max plan', { exact: true }).getByText('Sign in to choose a plan.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Current plan' })).toHaveCount(0)
})
